// src/components/hamburger/HamburgerMenu.vue
<script setup lang="ts">
/*
 * Copyright (c) 2024 by JWizard
 * Originally developed by Miłosz Gilga <https://miloszgilga.pl>
 */
import HamburgerMenuLink from './HamburgerMenuLink.vue';
import useUiStore from '@/store/uiStore';
import { buildDiscordOpenIdRoute } from '@/utils/utils';

const uiStore = useUiStore();
const orgLink = window.ORG_LINK;

function navigateToAddToDiscord(): void {
  window.open(window.INVITE_LINK, '_blank');
}

function authorizeViaDiscordOpenId(): void {
  document.location.href = buildDiscordOpenIdRoute();
}
</script>

<template>
  <div
    id="hamburger-menu"
    :class="[
      'fixed top-0 right-0 z-40',
      'w-80 h-screen',
      'p-4',
      'overflow-y-auto',
      'transition-transform translate-x-full',
      'bg-white dark:bg-slate-800',
    ]"
    tabindex="-1"
    aria-labelledby="drawer-right-label"
  >
    <button
      type="button"
      data-drawer-hide="hamburger-menu"
      aria-controls="hamburger-menu"
      :class="[
        'rounded-lg',
        'text-sm',
        'w-8 h-8',
        'absolute top-2.5 end-2.5',
        'inline-flex items-center justify-center',
        'bg-transparent',
        'text-slate-400 ',
        'hover:bg-slate-200 dark:hover:bg-slate-600',
        'hover:text-slate-800 dark:hover:text-white',
      ]"
    >
      <BIconX class="text-3xl" />
    </button>
    <div class="mt-10">
      <nav class="flex flex-col gap-y-3 mb-8">
        <ul>
          <HamburgerMenuLink link-href="/">
            {{ $t('home') }}
          </HamburgerMenuLink>
          <HamburgerMenuLink link-href="/commands">
            {{ $t('commands') }}
          </HamburgerMenuLink>
          <HamburgerMenuLink link-href="/contribute">
            {{ $t('contribute') }}
          </HamburgerMenuLink>
        </ul>
      </nav>
      <section class="flex flex-col gap-y-3 mb-8">
        <button
          type="button"
          :class="[
            'w-full',
            'font-medium',
            'rounded-full',
            'text-sm text-center',
            'py-2',
            'flex gap-x-3 justify-center items-center',
            'bg-slate-800 dark:bg-white',
            'text-white dark:text-slate-800',
            'hover:bg-slate-700 dark:hover:bg-slate-100',
          ]"
          @click="uiStore.toggleThemeMode()"
        >
          <BIconBrightnessHighFill v-if="uiStore.theme === 'dark'" />
          <BIconMoonStarsFill v-else />
          {{ $t('toggleTheme') }}
        </button>
        <a
          :href="orgLink"
          target="_blank"
          :class="[
            'w-full',
            'font-medium',
            'rounded-full',
            'text-sm text-center',
            'py-2',
            'flex gap-x-3 justify-center items-center',
            'bg-slate-800 dark:bg-white',
            'text-white dark:text-slate-800',
            'hover:bg-slate-700 dark:hover:bg-slate-100',
          ]"
        >
          <BIconGithub class="text-xl" />
          Github
        </a>
      </section>
      <section class="flex flex-col gap-y-3">
        <button
          type="button"
          :class="[
            'w-full',
            'font-medium',
            'rounded-full',
            'text-sm text-center',
            'py-2',
            'text-white',
            'bg-indigo-600 hover:bg-indigo-700',
            'dark:bg-indigo-600 dark:hover:bg-indigo-700',
          ]"
          @click="navigateToAddToDiscord"
        >
          {{ $t('addToDiscord') }}
        </button>
        <button
          type="button"
          :class="[
            'w-full',
            'font-medium',
            'rounded-full',
            'text-sm text-center',
            'py-2',
            'border',
            'hover:bg-gray-100',
            'border-gray-300 dark:border-gray-600 dark:hover:border-gray-700',
            'bg-white dark:bg-gray-800',
            'text-gray-900 dark:text-white',
          ]"
          @click="authorizeViaDiscordOpenId"
        >
          {{ $t('login') }}
        </button>
      </section>
    </div>
  </div>
</template>

// src/components/header/HamburgerMenu.tsx
/*
 * Copyright (c) 2024 by JWizard
 * Originally developed by Miłosz Gilga <https://miloszgilga.pl>
 */
import { Dispatch, SetStateAction } from 'react';
import { useTranslation } from 'react-i18next';
import {
  BsFillBrightnessHighFill,
  BsFillMoonStarsFill,
  BsGithub,
  BsX,
} from 'react-icons/bs';
import { styled } from 'styled-components';
import config from '@/config';
import { buildDiscordOpenIdRoute, openNewTab } from '@/utils';
import { useDarkMode } from '@rbnd/react-dark-mode';
import { JWizardUi } from '../ui';
import HamburgerMenuLink from './HamburgerMenuLink';

type Props = {
  isOpen: boolean;
  onCloseCallback: Dispatch<SetStateAction<boolean>>;
};

const HamburgerMenu: React.FC<Props> = ({
  isOpen,
  onCloseCallback,
}): JSX.Element => {
  const { mode, setMode } = useDarkMode();
  const { t } = useTranslation();

  const openIdRoute = buildDiscordOpenIdRoute();

  return (
    <Container $isOpen={isOpen} tabIndex={-1}>
      <CloseButton onClick={() => onCloseCallback(false)}>
        <BsX size={25} />
      </CloseButton>
      <ElementsWrapper>
        <SectionWrapper>
          <ul>
            <HamburgerMenuLink to="commands" />
            <HamburgerMenuLink to="contribute" />
          </ul>
        </SectionWrapper>
        <SectionWrapper>
          <JWizardUi.Button
            styleType="light"
            role="link"
            Icon={
              mode === 'dark' ? BsFillBrightnessHighFill : BsFillMoonStarsFill
            }
            onClick={() => setMode(mode === 'dark' ? 'light' : 'dark')}>
            {t('toggleTheme')}
          </JWizardUi.Button>
          <JWizardUi.Button
            styleType="light"
            role="link"
            Icon={BsGithub}
            onClick={() => openNewTab(config.orgLink)}>
            Github
          </JWizardUi.Button>
        </SectionWrapper>
        <SectionWrapper>
          <JWizardUi.Button
            styleType="theme"
            role="link"
            onClick={() => openNewTab(config.inviteLink)}>
            {t('addToDiscord')}
          </JWizardUi.Button>
          <JWizardUi.Button
            styleType="outlineLight"
            role="link"
            onClick={() => openNewTab(openIdRoute, true)}>
            {t('login')}
          </JWizardUi.Button>
        </SectionWrapper>
      </ElementsWrapper>
    </Container>
  );
};

const Container = styled.div<{ $isOpen: boolean }>`
  position: fixed;
  top: 0;
  right: 0;
  z-index: 40;
  width: 350px;
  height: 100vh;
  padding: var(--space-4);
  overflow-y: auto;
  transition: transform var(--duration);
  transform: translateX(${({ $isOpen }) => ($isOpen ? '0' : '100%')});
  background-color: var(--hamburger-menu-bg);
  box-shadow: var(--base-shadow);
`;

const CloseButton = styled.button`
  font-size: var(--font-sm);
  width: 30px;
  height: 30px;
  position: absolute;
  top: 10px;
  right: 10px;
  display: inline-flex;
  justify-content: center;
  align-items: center;
  background-color: transparent;
  color: var(--tint-color-400);
  border-radius: var(--button-radius);
  &:hover {
    color: var(--hamburger-menu-close-btn-hover-fg);
    background-color: var(--hamburger-menu-close-btn-hover-bg);
  }
`;

const ElementsWrapper = styled.div`
  margin-top: var(--space-10);
  display: flex;
  flex-direction: column;
  row-gap: var(--space-8);
`;

const SectionWrapper = styled.section`
  display: flex;
  flex-direction: column;
  row-gap: var(--space-3);
`;

export default HamburgerMenu;
