// src/components/hamburger/HamburgerMenuLink.vue
<script setup lang="ts">
/*
 * Copyright (c) 2024 by JWizard
 * Originally developed by Miłosz Gilga <https://miloszgilga.pl>
 */
type TProps = {
  linkHref: string;
};

const props = defineProps<TProps>();
</script>

<template>
  <li>
    <router-link
      :class="[
        'block ',
        'font-medium',
        'py-2',
        'w-full',
        'text-slate-700 dark:text-slate-200',
        'hover:text-indigo-600 dark:hover:text-indigo-500',
      ]"
      :to="props.linkHref"
    >
      <slot />
    </router-link>
  </li>
</template>

// src/components/header/HamburgerMenuLink.tsx
/*
 * Copyright (c) 2024 by JWizard
 * Originally developed by Miłosz Gilga <https://miloszgilga.pl>
 */
import { useTranslation } from 'react-i18next';
import { Link } from 'react-router-dom';
import { styled } from 'styled-components';

type Props = {
  to: string;
};

const HamburgerMenuLink: React.FC<Props> = ({ to }): JSX.Element => {
  const { t } = useTranslation();

  return (
    <li>
      <LinkElement to={`/${to}`}>{t(to)}</LinkElement>
    </li>
  );
};

const LinkElement = styled(Link)`
  display: block;
  font-weight: 500;
  padding: var(--space-2) 0;
  width: 100%;
  color: var(--hamburger-menu-link-fg);
  &:hover {
    color: var(--hamburger-menu-link-hover-fg);
  }
`;

export default HamburgerMenuLink;
