// src/components/header/MainHeader.vue
<script setup lang="ts">
/*
 * Copyright (c) 2024 by JWizard
 * Originally developed by Miłosz Gilga <https://miloszgilga.pl>
 */
import { computed, reactive, watch } from 'vue';
import HamburgerMenu from '../hamburger/HamburgerMenu.vue';
import HeaderLink from './HeaderLink.vue';
import HeaderTooltipButton from './HeaderTooltipButton.vue';
import { storeToRefs } from 'pinia';
import useUiStore from '@/store/uiStore';
import { buildDiscordOpenIdRoute } from '@/utils/utils';

type TProps = {
  headerFor: 'default' | 'root';
};

type TState = {
  isRoot: boolean;
};

const props = defineProps<TProps>();
const uiStore = useUiStore();

const state = reactive<TState>({
  isRoot: true,
});

const isRoot = computed(() => state.isRoot);
const { theme } = storeToRefs(uiStore);

watch(
  () => props.headerFor,
  (curr) => (state.isRoot = curr === 'root'),
);

function navigateToGithubRepo(): void {
  window.open(window.ORG_LINK, '_blank');
}

function navigateToAddToDiscord(): void {
  window.open(window.INVITE_LINK, '_blank');
}

function authorizeViaDiscordOpenId(): void {
  document.location.href = buildDiscordOpenIdRoute();
}
</script>

<template>
  <header
    :class="[
      'z-10',
      'w-full',
      { 'border-b border-slate-300 dark:border-slate-700': !isRoot },
      { 'backdrop-blur-sm': !isRoot },
      { fixed: !isRoot },
      isRoot ? 'bg-indigo-600' : 'bg-white/40 dark:bg-slate-800/40',
    ]"
  >
    <div
      :class="[
        'flex justify-between items-center',
        'mx-auto',
        'px-3 py-5',
        'max-w-[1280px] w-full',
      ]"
    >
      <div class="flex items-center">
        <router-link to="/" class="flex items-center">
          <img
            :src="`/logo/logo-${isRoot ? 'white' : 'color'}.svg`"
            alt="logo"
            width="40px"
            height="40px"
          />
          <p
            :class="[
              'font-logo',
              'text-2xl',
              'ms-2 -mt-[5px]',
              'dark:text-white',
              isRoot ? 'text-white' : 'text-slate-800',
            ]"
          >
            JWizard
          </p>
        </router-link>
        <ul class="flex items-center ms-8 gap-x-4">
          <HeaderLink :is-for-root-header="isRoot" link-href="/">
            {{ $t('home') }}
          </HeaderLink>
          <HeaderLink :is-for-root-header="isRoot" link-href="/commands">
            {{ $t('commands') }}
          </HeaderLink>
          <HeaderLink :is-for-root-header="isRoot" link-href="/contribute">
            {{ $t('contribute') }}
          </HeaderLink>
        </ul>
      </div>
      <nav class="flex items-center">
        <ul class="hidden md:flex gap-x-1 items-center">
          <HeaderTooltipButton
            :is-for-root-header="isRoot"
            tooptip-id="theme-tooltip"
            :tooltip-text="$t('toggleTheme')"
            @on-click-button="uiStore.toggleThemeMode()"
          >
            <BIconBrightnessHighFill v-if="theme === 'dark'" />
            <BIconMoonStarsFill v-else />
          </HeaderTooltipButton>
          <HeaderTooltipButton
            :is-for-root-header="isRoot"
            tooptip-id="github-tooltip"
            :tooltip-text="$t('goToGithubRepository')"
            @on-click-button="navigateToGithubRepo"
          >
            <BIconGithub class="text-xl" />
          </HeaderTooltipButton>
          <li>
            <button
              type="button"
              :class="[
                'font-medium',
                'rounded-full',
                'text-sm text-center',
                'px-4 py-2',
                'text-white',
                isRoot
                  ? 'bg-slate-900 hover:bg-slate-800'
                  : 'bg-indigo-600 hover:bg-indigo-700',
                isRoot
                  ? 'dark:bg-gray-900 dark:hover:bg-gray-800'
                  : 'dark:bg-indigo-600 dark:hover:bg-indigo-700',
              ]"
              @click="navigateToAddToDiscord"
            >
              {{ $t('addToDiscord') }}
            </button>
          </li>
          <li>
            <button
              type="button"
              :class="[
                'font-medium',
                'rounded-full',
                'text-sm text-center',
                'px-4 py-2',
                'border',
                'hover:bg-gray-100',
                isRoot
                  ? 'border-white'
                  : 'border-gray-300 dark:border-gray-600 dark:hover:border-gray-700',
                isRoot ? 'bg-white' : 'bg-white dark:bg-gray-800',
                isRoot ? 'text-gray-900' : 'text-gray-900 dark:text-white',
              ]"
              @click="authorizeViaDiscordOpenId"
            >
              {{ $t('login') }}
            </button>
          </li>
        </ul>
        <div class="text-center md:hidden">
          <button
            class="text-slate-800 dark:text-white text-3xl p-1"
            type="button"
            data-drawer-target="hamburger-menu"
            data-drawer-show="hamburger-menu"
            data-drawer-placement="right"
            aria-controls="hamburger-menu"
          >
            <BIconList />
          </button>
        </div>
      </nav>
    </div>
  </header>
  <HamburgerMenu />
</template>

// src/components/header/MainHeader.tsx
/*
 * Copyright (c) 2024 by JWizard
 * Originally developed by Miłosz Gilga <https://miloszgilga.pl>
 */
import { createContext, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { BsList } from 'react-icons/bs';
import {
  BsFillBrightnessHighFill,
  BsFillMoonStarsFill,
  BsGithub,
} from 'react-icons/bs';
import { Link, useLocation } from 'react-router-dom';
import { css, styled } from 'styled-components';
import config from '@/config';
import { devices } from '@/styles/global';
import { buildDiscordOpenIdRoute, openNewTab } from '@/utils';
import { useDarkMode } from '@rbnd/react-dark-mode';
import { JWizardUi } from '../ui';
import HamburgerMenu from './HamburgerMenu';
import HeaderLink from './HeaderLink';

export type IsRootProps = {
  isRoot: boolean;
};

export const IsRootContext = createContext<IsRootProps>({ isRoot: false });

const MainHeader: React.FC = (): JSX.Element => {
  const [isOpen, setIsOpen] = useState<boolean>(false);
  const location = useLocation();
  const { t } = useTranslation();
  const { mode, setMode } = useDarkMode();

  const isRoot = location.pathname === '/';
  const openIdRoute = buildDiscordOpenIdRoute();

  return (
    <HeaderContainer $isRoot={isRoot}>
      <HeaderWrapper>
        <HeaderSection>
          <HomeLink to="/">
            <img
              src={`/logo/logo-${isRoot ? 'white' : 'color'}.svg`}
              alt="logo"
              width={40}
              height={40}
            />
            <HomeParagraph $isRoot={isRoot}>JWizard</HomeParagraph>
          </HomeLink>
          <IsRootContext.Provider value={{ isRoot }}>
            <HeaderNavigation>
              <HeaderLink to="/commands" i18nLabel="commands" />
              <HeaderLink to="/contribute" i18nLabel="contribute" />
            </HeaderNavigation>
          </IsRootContext.Provider>
        </HeaderSection>
        <HeaderSection>
          <HeaderRightList>
            <JWizardUi.TooltipButton
              styleType="light"
              placement="bottom"
              Icon={
                mode === 'dark' ? BsFillBrightnessHighFill : BsFillMoonStarsFill
              }
              tooltipI18nLabel="toggleTheme"
              onClick={() => setMode(mode === 'dark' ? 'light' : 'dark')}
            />
            <JWizardUi.TooltipButton
              styleType="light"
              placement="bottom"
              Icon={BsGithub}
              tooltipI18nLabel="goToGithubRepository"
              onClick={() => openNewTab(config.orgLink)}
            />
            <JWizardUi.Button
              styleType={isRoot ? 'agnosticDark' : 'theme'}
              onClick={() => openNewTab(config.inviteLink)}>
              {t('addToDiscord')}
            </JWizardUi.Button>
            <JWizardUi.Button
              styleType={isRoot ? 'agnosticLight' : 'light'}
              onClick={() => openNewTab(openIdRoute, true)}>
              {t('login')}
            </JWizardUi.Button>
          </HeaderRightList>
          <HeaderHamburgerButton
            $isRoot={isRoot}
            onClick={() => setIsOpen(true)}>
            <BsList size={25} />
          </HeaderHamburgerButton>
        </HeaderSection>
      </HeaderWrapper>
      <HamburgerMenu isOpen={isOpen} onCloseCallback={setIsOpen} />
    </HeaderContainer>
  );
};

const HeaderContainer = styled.header<{ $isRoot: boolean }>`
  position: ${({ $isRoot }) => ($isRoot ? 'relative' : 'fixed')};
  z-index: 10;
  width: 100%;
  ${({ $isRoot }) =>
    $isRoot
      ? css`
          background-color: var(--theme-color-600);
        `
      : css`
          backdrop-filter: blur(4px);
          border-bottom-width: 1px;
          border-color: var(--header-border);
          background-color: var(--header-bg);
        `};
`;

const HeaderWrapper = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin: 0 auto;
  padding: var(--space-3) var(--space-5);
  max-width: var(--br-xl);
  width: 100%;
`;

const HeaderSection = styled.section`
  display: flex;
  align-items: center;
`;

const HomeLink = styled(Link)`
  display: flex;
  align-items: center;
`;

const HomeParagraph = styled.p<{ $isRoot: boolean }>`
  font-family: var(--font-logo);
  font-size: var(--font-2xl);
  margin-left: var(--space-2);
  margin-top: calc(var(--space-1) * -1);
  color: var(
    ${({ $isRoot }) => ($isRoot ? '--header-p-root-fg' : '--header-p-fg')}
  );
`;

const HeaderNavigation = styled.ul`
  display: flex;
  align-items: center;
  margin-left: var(--space-8);
  column-gap: var(--space-4);
`;

const HeaderRightList = styled.div`
  display: none;
  align-items: center;
  column-gap: var(--space-2);
  @media only ${devices.md} {
    display: flex;
  }
`;

const HeaderHamburgerButton = styled.button<{ $isRoot: boolean }>`
  display: block;
  text-align: center;
  color: var(
    ${({ $isRoot }) => ($isRoot ? '--light-color-100' : '--hamburger-bars-fg')}
  );
  @media only ${devices.md} {
    display: none;
  }
`;

export default MainHeader;
