// src/components/MainFooter.vue
<script setup lang="ts">
/*
 * Copyright (c) 2024 by JWizard
 * Originally developed by Miłosz Gilga <https://miloszgilga.pl>
 */
import { availableLocales } from '@/i18n';
import useUiStore from '@/store/uiStore';

const uiStore = useUiStore();
const year = new Date().getFullYear();

function navigateToAddToDiscord(): void {
  window.open(window.INVITE_LINK, '_blank');
}
</script>

<template>
  <footer class="bg-indigo-600 text-white">
    <div
      :class="[
        'max-w-[1280px] w-full',
        'mx-auto',
        'pt-10 pb-3 px-3 py-5',
        'flex flex-col items-center',
      ]"
    >
      <section
        :class="[
          'flex flex-col-reverse md:flex-row ',
          'justify-between items-center',
          'w-full',
          'mb-8',
        ]"
      >
        <p
          :class="[
            'text-center md:text-left',
            'md:me-20',
            'max-w-[900px]',
            'text-indigo-300',
          ]"
        >
          {{ $t('description') }}
        </p>
        <router-link
          to="/"
          class="flex items-center gap-x-1 flex-shrink-0 mb-10 md:mb-0"
        >
          <img
            src="/logo/logo-white.svg"
            alt="logo"
            width="40px"
            height="40px"
          />
          <p class="font-logo text-2xl ms-2">JWizard</p>
        </router-link>
      </section>
      <section
        :class="[
          'flex flex-col md:flex-row',
          'justify-between md:items-center',
          ' w-full',
        ]"
      >
        <nav class="font-medium mb-10 md:mb-0">
          <ul class="flex gap-x-6 justify-center md:justify-start">
            <li class="text-sm">
              <router-link to="/" class="hover:underline">
                {{ $t('home') }}
              </router-link>
            </li>
            <li class="-mt-[3px]">&bull;</li>
            <li class="text-sm">
              <router-link to="/contribute" class="hover:underline">
                {{ $t('contribute') }}
              </router-link>
            </li>
            <li class="-mt-[3px]">&bull;</li>
            <li class="text-sm">
              <router-link to="/commands" class="hover:underline">
                {{ $t('commands') }}
              </router-link>
            </li>
          </ul>
        </nav>
        <div class="flex gap-x-2">
          <button
            type="button"
            :class="[
              'font-medium',
              'rounded-full',
              'text-sm text-center',
              'px-4 py-2',
              'text-slate-950',
              'basis-[50%] md:basis-auto',
              'bg-white hover:bg-slate-200',
            ]"
            @click="navigateToAddToDiscord"
          >
            {{ $t('addToDiscord') }}
          </button>
          <select
            v-model="uiStore.locale"
            :class="[
              'text-center text-sm',
              'basis-[50%] md:basis-auto',
              'cursor-pointer',
              'w-[140px]',
              'rounded-full',
              'font-medium',
              'block',
              'py-2',
              'border-none',
              'bg-slate-900',
              'text-white',
              'focus:ring-white',
            ]"
          >
            <option
              v-for="(locale, localeId) in availableLocales"
              :key="localeId"
              :value="localeId"
            >
              {{ locale.label }}
            </option>
          </select>
        </div>
      </section>
      <hr class="border-0 h-px bg-indigo-500 w-full mt-6 mb-4" />
      <section class="my-3">
        <p class="text-sm text-indigo-400">
          &copy; {{ year }} by JWizard. All rights reserved.
        </p>
      </section>
    </div>
  </footer>
</template>

// src/components/footer/MainFooter.tsx
/*
 * Copyright (c) 2024 by JWizard
 * Originally developed by Miłosz Gilga <https://miloszgilga.pl>
 */
import { useTranslation } from 'react-i18next';
import { Link } from 'react-router-dom';
import styled from 'styled-components';
import config from '@/config';
import { breakpoints, devices, space } from '@/styles/global';
import { openNewTab } from '@/utils';
import { JWizardUi } from '../ui';
import LanguageSelect from './LanguageSelect';
import NavigationLinkElement from './NavigationLinkElement';

const MainFooter: React.FC = (): JSX.Element => {
  const { t } = useTranslation();
  const year = new Date().getFullYear();

  return (
    <FooterContainer>
      <FooterWrapper>
        <DescriptionWithLogoSection>
          <Description>{t('description')}</Description>
          <LogoLink to="/">
            <img src="/logo/logo-white.svg" alt="logo" width={40} height={40} />
            <LogoText>JWizard</LogoText>
          </LogoLink>
        </DescriptionWithLogoSection>
        <NavigationWithButtonsSection>
          <Navigation>
            <NavigationList>
              <NavigationLinkElement to="/" i18nLabel="home" />
              <NavigationLinkElement to="commands" i18nLabel="commands" />
              <NavigationLinkElement
                to="contribute"
                i18nLabel="contribute"
                isLast
              />
            </NavigationList>
          </Navigation>
          <ButtonsSection>
            <JWizardUi.Button
              styleType="agnosticLight"
              onClick={() => openNewTab(config.inviteLink)}>
              {t('addToDiscord')}
            </JWizardUi.Button>
            <LanguageSelect />
          </ButtonsSection>
        </NavigationWithButtonsSection>
        <Separator />
        <CopyrightContainer>
          <CopyrightParagraph>&copy; {year} by JWizard.</CopyrightParagraph>
          <CopyrightParagraph>Build: {config.buildVersion}</CopyrightParagraph>
        </CopyrightContainer>
      </FooterWrapper>
    </FooterContainer>
  );
};

const FooterContainer = styled.footer`
  color: var(--gray-color-0);
  background-color: var(--gray-color-800);
`;

const FooterWrapper = styled.div`
  max-width: ${breakpoints.xl};
  width: 100%;
  margin: 0 auto;
  padding: ${space(10)} ${space(5)} ${space(3)} ${space(5)};
  display: flex;
  flex-direction: column;
  align-items: center;
`;

const DescriptionWithLogoSection = styled.section`
  display: flex;
  flex-direction: column-reverse;
  justify-content: space-between;
  align-items: center;
  width: 100%;
  margin-bottom: ${space(8)};
  @media only ${devices.md} {
    flex-direction: row;
  }
`;

const Description = styled.p`
  text-align: center;
  max-width: 900px;
  font-weight: 500;
  color: var(--gray-color-500);
  @media only ${devices.md} {
    text-align: left;
    margin-right: ${space(20)};
  }
`;

const LogoLink = styled(Link)`
  display: flex;
  align-items: center;
  flex-shrink: 0;
  margin-bottom: ${space(10)};
  row-gap: ${space(1)};
  @media only ${devices.md} {
    margin-bottom: 0;
  }
`;

const LogoText = styled.p`
  font-family: var(--font-logo);
  font-size: var(--font-2xl);
  line-height: var(--line-height-2xl);
  margin-left: ${space(2)};
  color: var(--gray-color-0);
`;

const NavigationWithButtonsSection = styled.section`
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  width: 100%;
  @media only ${devices.md} {
    flex-direction: row;
    align-items: center;
  }
`;

const Navigation = styled.nav`
  margin-bottom: ${space(5)};
  @media only ${devices.md} {
    margin-bottom: 0;
  }
`;

const NavigationList = styled.ul`
  display: flex;
  row-gap: ${space(6)};
  justify-content: center;
  @media only ${devices.md} {
    justify-content: start;
  }
`;

const ButtonsSection = styled.div`
  display: flex;
  justify-content: center;
  column-gap: ${space(2)};
  @media only ${devices.md} {
    justify-content: flex-start;
  }
`;

const Separator = styled.hr`
  border: 0;
  height: 1px;
  background-color: var(--gray-color-600);
  width: 100%;
  margin: ${space(6)} 0 ${space(4)};
`;

const CopyrightContainer = styled.section`
  margin: ${space(3)} 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  width: 100%;
  font-size: var(--font-sm);
  @media only ${devices.md} {
    flex-direction: row;
    justify-content: space-between;
  }
`;

const CopyrightParagraph = styled.p`
  color: var(--gray-color-500);
  font-weight: 500;
  margin: ${space(1)} 0;
`;

export default MainFooter;
